"""fixed some notification functionality

Revision ID: 075a7ff32e2f
Revises: 856f5977825d
Create Date: 2022-10-30 15:11:50.229355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075a7ff32e2f'
down_revision = '856f5977825d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('end_url', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'end_url')
    # ### end Alembic commands ###
