"""empty message

Revision ID: 096227f1771a
Revises: d0f38a2cb5b1
Create Date: 2022-12-29 22:50:19.431079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096227f1771a'
down_revision = 'd0f38a2cb5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###
