"""empty message

Revision ID: 3b178783a880
Revises: 4b4a28fba5b1
Create Date: 2022-12-29 23:01:33.175375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b178783a880'
down_revision = '4b4a28fba5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited_time', sa.DateTime(), nullable=True))
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.BOOLEAN(), nullable=True))
    op.drop_column('post', 'edited_time')
    # ### end Alembic commands ###
