"""empty message

Revision ID: 4b4a28fba5b1
Revises: c40f9822bcb9
Create Date: 2022-12-29 22:58:29.407569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b4a28fba5b1'
down_revision = 'c40f9822bcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited_time', sa.DateTime(), nullable=True))
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.BOOLEAN(), nullable=True))
    op.drop_column('post', 'edited_time')
    # ### end Alembic commands ###
