"""empty message

Revision ID: c40f9822bcb9
Revises: 096227f1771a
Create Date: 2022-12-29 22:57:32.402087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40f9822bcb9'
down_revision = '096227f1771a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited_time', sa.DateTime(), nullable=True))
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.BOOLEAN(), nullable=True))
    op.drop_column('post', 'edited_time')
    # ### end Alembic commands ###
