"""editing fix

Revision ID: d0f38a2cb5b1
Revises: b84f2d6e832e
Create Date: 2022-12-29 22:46:05.317266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f38a2cb5b1'
down_revision = 'b84f2d6e832e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###
