"""Add rep and post likes.

Revision ID: f2bfbbc7a9be
Revises: b45942373176
Create Date: 2023-01-18 01:40:01.530581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bfbbc7a9be'
down_revision = 'b45942373176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('reply_to_comment')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('elo')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_comment', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
